//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2test.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user105dbEntities : DbContext
    {
        public user105dbEntities()
            : base("name=user105dbEntities")
        {
        }

        private static user105dbEntities _context;

        public static user105dbEntities GetContext()
        {
            if (_context == null)
                _context = new user105dbEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Flag> Flags { get; set; }
        public virtual DbSet<Istoria_pokupok> Istoria_pokupok { get; set; }
        public virtual DbSet<Kategoria> Kategorias { get; set; }
        public virtual DbSet<Podkategoria> Podkategorias { get; set; }
        public virtual DbSet<Pol> Pols { get; set; }
        public virtual DbSet<Poseshenie_client> Poseshenie_client { get; set; }
        public virtual DbSet<Proizvoditel> Proizvoditels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teg> Tegs { get; set; }
        public virtual DbSet<Tovar> Tovars { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Usluga> Uslugas { get; set; }
    }
}
