//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2test.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Istoria_pokupok
    {
        public int Id_IP { get; set; }
        public int Id_tovar { get; set; }
        public System.DateTime Date_pokupki { get; set; }
        public int Kolvo { get; set; }
        public int Id_client { get; set; }
        public int Id_usluga { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tovar Tovar { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
