//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2test.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poseshenie_client
    {
        public int Id_PC { get; set; }
        public int Id_client { get; set; }
        public System.DateTime Date_poseshenie { get; set; }
        public System.TimeSpan Time_poseshenie { get; set; }
        public int Dlitelnost_poseshenie { get; set; }
        public byte[] Photo_DO { get; set; }
        public byte[] Photo_POSLE { get; set; }
        public Nullable<int> Id_usluga { get; set; }
        public Nullable<int> Id_sotrudnik { get; set; }
        public string Primechanie { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
